# Medicine Items
herb = "Herb"
love_water = "Love Water"
world_dew = "World Dew"
potion = "Potion"
elf_water = "Elf Water"
antidote = "Antidote"
moon_herb = "Moon Herb"
laurel = "Laurel"
awake_sand = "Awake Sand"
sky_bell = "Sky Bell"
sage_rock = "Sage Rock"
world_leaf = "World Leaf"

# Stat Seeds
atk_seed = "ATK Seed"
def_seed = "DEF Seed"
agl_seed = "AGL Seed"
int_seed = "INT Seed"
life_acorn = "Life Acorn"
mystic_nut = "Mystic Nut"

# Personality Books
quest_book = "Quest Book"
horror_book = "Horror Book"
be_nice_book = "Be Nice Book"
cheater_book = "Cheater Book"
smart_book = "Smart Book"
comedy_book = "Comedy Book"

# Meat
beef_jerky = "Beef Jerky"
pork_chop = "Pork Chop"
rib = "Rib"
sirloin = "Sirloin"
bad_meat = "Bad Meat"
meteorb = "MeteOrb"

# Encounter Items
beast_tail = "Beast Tail"
repellent = "Repellent"
shiny_harp = "Shiny Harp"

# Staves
mist_staff = "Mist Staff"
friend_staff = "Friend Staff"
wind_staff = "Wind Staff"
bolt_staff = "Bolt Staff"
snow_staff = "Snow Staff"
fire_staff = "Fire Staff"

# Travel Items
warp_staff = "Warp Staff"
warp_wing = "Warp Ring"
exit_bell = "Exit Bell"
bookmark = "Bookmark"
tiny_medal = "Tiny Medal"
gold_pass = "Gold Pass"
log_twig = "Log Twig"

# Key Items
water_call = "Water Call"
moon_rock = "Moon Rock"
crest = "Crest"
yuna_soul = "Yuna Soul"
sleep_herb = "Sleep Herb"
change_staff = "Change Staff"
tidal_bell = "Tidal Bell"
har_mirror = "Har Mirror"
sky_shield = "Sky Shield"
heaven_helmet = "Heaven Helmet"
heaven_armor = "Heaven Armor"
heaven_sword = "Heaven Sword"
wiz_stone = "Wiz Stone"
pretty_ring = "Pretty Ring"

# Stat Boost Equipment
vit_belt = "VIT Belt"
draco_belt = "Draco Belt"
magic_belt = "Magic Belt"
odd_belt = "Odd Belt"
stone_fang = "Stone Fang"
steel_fang = "Steel Fang"
merm_scale = "Merm Scale"
drak_scale = "Drak Scale"
agl_ring = "AGL Ring"
starry_ring = "Starry Ring"
smart_hat = "Smart Hat"
wise_hat = "Wise Hat"

# Resistance Equipment
magic_cape = "Magic Cape"
draco_cape = "Draco Cape"
silver_cape = "Silver Cape"
gold_cape = "Gold Cape"
plat_cape = "Platinum Cape"
orca_cape = "Orca Cape"
brave_cape = "Brave Cape"
d_scale = "D-Scale"

# Growth Equipment
life_ring = "Life Ring"
divine_ring = "Divine Ring"
war_ring = "War Ring"
mage_ring = "Mage Ring"
fight_ring = "Fight Ring"
sailor_ring = "Sailor Ring"
thief_ring = "Thief Ring"
cleric_ring = "Cleric Ring"

# World Keys
greatlog_key = "GreatLog Key"
oasis_key = "Oasis Key"
pirate_key = "Pirate Key"
ice_key = "Ice Key"
sky_key = "Sky Key"
limbo_key = "Limbo Key"
elf_key = "Elf Key"
lonely_key = "Lonely Key"
traveler_key = "Traveler Key"
brawn_key = "Brawn Key"
baffle_key = "Baffle Key"
soul_key = "Soul Key"
magic_key = "Magic Key"